# Category constants
CATEGORY_TITLE_LENGTH = 32
CATEGORY_SLUG_LENGTH = 32

# Subcategory constants
SUBCATEGORY_TITLE_LENGTH = 32
SUBCATEGORY_SLUG_LENGTH = 32

# Page constants
PAGE_TITLE_LENGTH = 32
PAGE_SLUG_LENGTH = 32

# PageSection constants
PAGE_SECTION_TITLE_LENGTH = 32
PAGE_SECTION_TYPE_LENGTH = 8

# ImageSection constants
IMAGE_SECTION_PATH_LENGTH = 255
