# Category constants
CATEGORY_TITLE_LENGTH = 32
CATEGORY_SLUG_LENGTH = 32
CATEGORY_HTML_CLASS_LENGTH = 32

# Subcategory constants
SUBCATEGORY_TITLE_LENGTH = 32
SUBCATEGORY_SLUG_LENGTH = 32
SUBCATEGORY_HTML_CLASS_LENGTH = 32

# Page constants
PAGE_TITLE_LENGTH = 32
PAGE_SLUG_LENGTH = 32
PAGE_COVER_LINK_LENGTH = 255

# PageSection constants
PAGE_SECTION_TYPE_LENGTH = 8
PAGE_SECTION_TITLE_LENGTH = 32
PAGE_SECTION_SLUG_LENGTH = 32

# ImageSection constants
IMAGE_SECTION_PATH_LENGTH = 255

# Link constants
LINK_LINK_LENGTH = 32
LINK_LINKED_MODELS = ['Page', 'Subcategory', 'Category', 'NewsItem']
