# View constants
NEWS_ITEMS_PER_PAGE = 5
NEWS_PREVIEW_LENGTH = 300
ARCHIVE_URL = 'archief'
BLUEPRINT_TITLE = 'Nieuws'

# NewsItem constants
NEWS_ITEM_TITLE_LENGTH = 32
NEWS_ITEM_AUTHOR_LENGTH = 32
NEWS_ITEM_COVER_IMAGE_URL_LENGTH = 255
