# view constants
ALBUMS_PER_PAGE = 5
ARCHIVE_URL = 'archief'
BLUEPRINT_TITLE = "Foto's"

# Album constants
ALBUM_TITLE_LENGTH = 32
ALBUM_AUTHOR_LENGTH = 32

# Image constants
IMAGE_TITLE_LENGTH = 32
IMAGE_IMAGE_URL_LENGTH = 255
